--- 
development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: development
  pool: 5
  timeout: 5000
production: 
  adapter: postgresql
  database: production
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
test: 
  adapter: postgresql
  database: test
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000